// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SignalIrBasicChat.Models;

public partial class Conversation
{
    [Key]
    public int nConversationId { get; set; }

    public int nUserA { get; set; }

    public int nUserB { get; set; }

    [InverseProperty("nConversation")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    [ForeignKey("nUserA")]
    [InverseProperty("ConversationnUserANavigations")]
    public virtual User nUserANavigation { get; set; }

    [ForeignKey("nUserB")]
    [InverseProperty("ConversationnUserBNavigations")]
    public virtual User nUserBNavigation { get; set; }
}