// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SignalIrBasicChat.Models;

public partial class Message
{
    [Key]
    public int nMessageId { get; set; }

    public int nConversationId { get; set; }

    public int nUserId { get; set; }

    [Required]
    [StringLength(250)]
    public string cMessage { get; set; }

    [ForeignKey("nConversationId")]
    [InverseProperty("Messages")]
    public virtual Conversation nConversation { get; set; }

    [ForeignKey("nUserId")]
    [InverseProperty("Messages")]
    public virtual User nUser { get; set; }
}