// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SignalIrBasicChat.Models;

public partial class User
{
    [Key]
    public int nUserId { get; set; }

    [Required]
    [StringLength(50)]
    public string cUsername { get; set; }

    [Required]
    [StringLength(50)]
    public string cPassword { get; set; }

    [Required]
    [StringLength(50)]
    public string cEmail { get; set; }

    public bool? bVerifiedEmail { get; set; }

    [InverseProperty("nUserANavigation")]
    public virtual ICollection<Conversation> ConversationnUserANavigations { get; set; } = new List<Conversation>();

    [InverseProperty("nUserBNavigation")]
    public virtual ICollection<Conversation> ConversationnUserBNavigations { get; set; } = new List<Conversation>();

    [InverseProperty("nUser")]
    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();
}