// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SignalIrBasicChat.Models;

[Keyless]
public partial class UserConversation
{
    public int nUserId { get; set; }

    public int nConversationId { get; set; }

    [ForeignKey("nConversationId")]
    public virtual Conversation nConversation { get; set; }

    [ForeignKey("nUserId")]
    public virtual User nUser { get; set; }
}